spring:
  application:
    name: cv-service
  zipkin:
    base-url: http://localhost:9411/
---
spring:
  profiles: zone1
eureka:
  instance:
    metadata-map:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: ${PORT:8081}

#spring:
#  profiles: zone2
#eureka:
#  instance:
#    metadata-map:
#      zone: zone2
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#server:
#  port: ${PORT:8082}






      #   registryFetchIntervalSeconds: 3
       #  shouldDisableDelta: true

   # instance:
    #  leaseRenewalIntervalInSeconds: 1
     #   leaseExpirationDurationInSeconds: 2






#eureka:
 # instance:
  #  metadata-map:
   #   zone: zone1
#client:
 # serviceUrl:
  #  defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

